import { Inter } from "next/font/google";
import "./globals.css";

import Provider from "./provider";
import Header from "@/components/Header"
import Navigate from "@/components/Navigate";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "comic-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">   
      <body className={inter.className}>
        <Provider>
          <Header/>
          <Navigate/>
          {children}      
          <Footer/>
        </Provider>
      </body>
    </html>
  );
}
