import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Provider from "./Provider";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "@/components/ui/toaster"




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "comic-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Provider>
            <Header />
            <NavBar />
            {children}
            <Toaster />
            <Footer />
          </Provider>
        </body>
      </html>
    </ClerkProvider >
  );
}
