import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import Header from "@/components/Header"
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Container from "@/components/Container";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "comic-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          <NavBar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
